# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db66fe21cdc0158a0a22623d758d191797e0c7002a373d0fe47a462755e227f18275d63bcb472876ff25ea535b5c05bb0283e36cc39d9d8004111467a7410965

test:
  secret_key_base: db5d5ad031e3f2a005da73f2efef01adaae433348010b08962bb8aeb67a396e6f025d2d8f6a42a39bc74c59f756602cfee38d4012246b495fec7a73538e80b07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
